apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-dashboard-pvc
  namespace: logging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: grafana-dashboard-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-dashboard-pv
  namespace: logging
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: X.X.X.X
    path: /export/grafana
  persistentVolumeReclaimPolicy: Retain

